// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.alembic_version */
export type AlembicVersionVersionNum = string & { __brand: 'AlembicVersionVersionNum' };

/** Represents the table public.alembic_version */
export default interface AlembicVersionTable {
  version_num: ColumnType<AlembicVersionVersionNum, AlembicVersionVersionNum, AlembicVersionVersionNum>;
}

export type AlembicVersion = Selectable<AlembicVersionTable>;

export type NewAlembicVersion = Insertable<AlembicVersionTable>;

export type AlembicVersionUpdate = Updateable<AlembicVersionTable>;
