// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type UsersId } from './Users';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.goals */
export type GoalsId = string & { __brand: 'GoalsId' };

/** Represents the table public.goals */
export default interface GoalsTable {
  id: ColumnType<GoalsId, GoalsId | undefined, GoalsId>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  /** The skill that the user wants to master, e.g. 'French speaking' */
  skill: ColumnType<string | null, string | null, string | null>;

  /** How well the user has mastered the skill, e.g. 'I know a few basic phrases and the present tense' */
  current_capability: ColumnType<string | null, string | null, string | null>;

  /** What the user wants to be able to do, e.g. 'Hold a basic conversation with my girlfriend's parents over lunch' */
  target_capability: ColumnType<string | null, string | null, string | null>;

  /** When the user wants to start learning */
  start_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  /** When the user wants to achieve their goal by */
  end_date: ColumnType<Date | null, Date | string | null, Date | string | null>;

  user_id: ColumnType<UsersId | null, UsersId | null, UsersId | null>;
}

export type Goals = Selectable<GoalsTable>;

export type NewGoals = Insertable<GoalsTable>;

export type GoalsUpdate = Updateable<GoalsTable>;
