// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type GoalsId } from './Goals';
import { type ColumnType, type Selectable, type Insertable, type Updateable } from 'kysely';

/** Identifier type for public.plans */
export type PlansId = string & { __brand: 'PlansId' };

/** Represents the table public.plans */
export default interface PlansTable {
  id: ColumnType<PlansId, PlansId | undefined, PlansId>;

  created_at: ColumnType<Date | null, Date | string | null, Date | string | null>;

  /** The skills to master */
  skills: ColumnType<unknown[], unknown[], unknown[]>;

  goal_id: ColumnType<GoalsId | null, GoalsId | null, GoalsId | null>;
}

export type Plans = Selectable<PlansTable>;

export type NewPlans = Insertable<PlansTable>;

export type PlansUpdate = Updateable<PlansTable>;
