// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import { type default as AlembicVersionTable } from './AlembicVersion';
import { type default as UsersTable } from './Users';
import { type default as GoalsTable } from './Goals';
import { type default as PlansTable } from './Plans';

export default interface PublicSchema {
  alembic_version: AlembicVersionTable;

  users: UsersTable;

  goals: GoalsTable;

  plans: PlansTable;
}
